### ISSUE TITLE
backport: logs splitting

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#100]
https://github.com/EOSIO/eos/pull/9184
https://github.com/EOSIO/eos/pull/9277
https://github.com/EOSIO/eos/pull/9821
https://github.com/EOSIO/eos/pull/9829
https://github.com/EOSIO/eos/pull/10037
https://github.com/EOSIO/eos/pull/10061
https://github.com/EOSIO/eos/pull/10548
https://github.com/EOSIO/eos/pull/10561

**Comment by matthewdarwin** [comment]
The key issues for log rotation is to capture 3 use cases:

- keep everything (existing 2.0) code
- keep some amount of blocks, and then throw out everything
- don't keep anything

Need to support blocks.log and ship.

**Comment by matthewdarwin** [comment]
--- below is sent to mandel upgrade telegram and a few other places ---

Hello all,

As part of mandel 3.1 plans, it has been previously discussed that the "blocks.log splitting feature" is a necessary requirement for the release to be acceptable to the community. Recently, a question arose, as to what is the actual requirements necessary for 3.1 related to this feature.

It is my (and a few other people's view) that the desirable list of features for mandel 3.1 is as follows:

1) keep all the blogs.log, in a single file, as per nodeos 2.0 (no change). Starts from beginning or based on a snapshot.

2) keep some recent blocks, in one file (or optionally more files at the discretion of the developers),  and remove old blocks when the configured number of blocks passes
  - this is less features than is in 2.1 where it can split files, move them to archive directory, and other things

3) don't store any blocks at all (this is a new feature, not in 2.1)

If you have opinions one way or another, please add thoughts to the github issues:
https://github.com/eosnetworkfoundation/mandel/issues/100
https://github.com/eosnetworkfoundation/mandel/issues/92

@daniel_keyes I suggest mentioning this in the next meeting.

**Comment by brianjohnson5972** [comment]
One thing to remember in this decision is that even if we have to do a re-write of the existing stride implementation for block-log and ship, the unit tests and integration tests are likely a direct port and I would estimate that (not sure if there are ship integration tests) between a 1 and 2 week effort. That, in my mind, would lean toward the existing design (that assumes that there are not identified disconnects between desired use-cases and how the strides feature works).

**Comment by spoonincode** [comment]
If the existing design can just be cherry-picked over, that would be a significant reason to take it as is. But my understanding was that it was interwoven with CFA pruning stuff. (I haven't actually looked, so feel free to correct me)

If it needs to be refactored at all, I would encourage refactoring for simplicity as long as the requirements allow for it. The requirements seem to simply be: allow setting a maximum size for block log & ship log; where 'size' can be implemented as either block count or total byte size. That should allow a fair bit of simplification in the design.

**Comment by matthewdarwin** [comment]
I would prefer number of blocks rather than size in bytes. It keeps things more predictable from a user perspective.  "I have 7 days of blocks". (of course it is less predicable from a disk space usage perspective)

**Comment by spoonincode** [comment]
bytes is probably easiest to implement because it's quite easy to just have a 1GB file (or whatever configured size) that is simple treated as a circular buffer that endlessly wraps around

**Comment by brianjohnson5972** [comment]
@spoonincode Kevin had assessed it as a re-write.  My point was just that there are extensive tests already written, that should be able to be used as-is, which would significantly reduce the re-write time versus creating a simpler design and implementing that.

The existing stride design is based off of a "stride"(range) of blocks, so it is blocks rather than size based.

**Comment by matthewdarwin** [comment]
PRs for this are merged into 3.1.0:

- https://github.com/eosnetworkfoundation/mandel/pull/342 block log pruning: optionally reduce disk usage of block log file during operation by periodically trimming blocks
- https://github.com/eosnetworkfoundation/mandel/pull/327 ship log pruning: optionally reduce disk usage of ship log files during operation by periodically trimming logs
-
