### ISSUE TITLE
Enhancement: Add API call to get earliest_block_available 

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#118]
originally: https://github.com/EOSIO/eos/issues/10008

/v1/chain/get_info tells you want is the last block available, but not the first block. Since nodeos can start from a snaphot and with 2.1 auto-remove old blocks, it would be nice to have a way to know which blocks are actually available.

Information could be added to the existing get_info API call.

Use case 1: The use case is that I was trying to sync blocks from a node for which the blocks were expired. So would like to create some sort of internal dashboard so I know how many blocks are available on which nodes. This requirement could also be fulfilled other ways.

Use case 2: From a public API endpoint point of view (eg validate.eosnation.io) it would be nice to know which is the first block available. Currently need to run multiple get_block queries to figure out which is the first block available.

**Comment by heifner** [comment]
Should just backport: https://github.com/EOSIO/eos/pull/11013 After block log splitting added to Mandel.

**Comment by heifner** [comment]
Seems there is a desire to name this `get_earliest_block_available`. See #176

**Comment by heifner** [comment]
Should also add `last_irreversible_block_time` https://github.com/EOSIO/eos/pull/9606 at the same time.
