### ISSUE TITLE
Will the new version of EOS support the utilization of multiple CPU cores

### ISSUE THREAD

**Issue by cppfuns** [eosnetworkfoundation/mandel#123]
Remember that the previous eosio version can only use a single core of the CPU. Will the new version support it?

**Comment by matthewdarwin** [comment]
Issue tracker is not the best place to ask questions.  Suggest to use EOSIO developers telegram or ENF discord #mandel channel.

Nodeos can use more than one core today. Multiple threads for handling http requests, for example. However the core blockchain logic is limited to a single CPU. Discussions are underway for how this might be improved in the future via Scalability+ working group. Don't expect anything in the short term.
