### ISSUE TITLE
restore pinned builds and binary packages

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#147]
#137 removes support for pinned builds and binary packages from Mandel. Well, as opined in that PR, those features have already been removed from Mandel by way of them being untested & unmaintained over the course of multiple Mandel releases (3.0 & 3.0.5). Truly, no one knows the working state of anything being removed in that PR.

Both pinned builds and binary packages are desirable features that clearly had a positive impact on usability when they were introduced in EOSIO. These features need to be reintroduced and fully supported.

Baseline criteria for competition of these features are, for all platforms supported, native packages (rpm, deb, etc) that are built with a compiler & boost combo which we have high confidence will not change for all package builds of a minor release (i.e. all releases from x.y.0 to x.y.n). These packages must be built by CI regularly (one would expect the CI to use the pinned compiler for each PR, etc). Users must also have the ability to independently build Mandel in the same configuration without it being too onerous. Taking it further and having these independent builds being completely reproducible to the binary packages provided by the Mandel team is probably more of a requirement captured in #36 instead of this issue.

Determining the platforms that are supported is not the goal of this issue. It's possible a given release of Mandel may only support a single platform, e.g. Ubuntu 20.04. In such a scenario a single .deb file that installs cleanly solely on 20.04 fulfills the requirement.

**Comment by spoonincode** [comment]
There is basic packaging support in #279

**Comment by matthewdarwin** [comment]
Basic support is working.  Close this issue?
