### ISSUE TITLE
replace websocketpp with boost beast as nodeos' HTTP server implemention 

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#148]
EOSIO/eos#10689 replaced the websocketpp with Boost Beast as the HTTP server implementation in nodeos. This is a positive improvement and should be done in Mandel. I'm not sure if the change set should be taken verbatim though. Should have a little investigation instead of being blindly cherry picked.

**Comment by stephenpdeos** [comment]
As per discussion in today's refinement, OCI team will circle back on comments in historical PR and put deeper consideration into what a better solution could look like. @spoonincode to comment in additional details as needed.
