### ISSUE TITLE
snapshot json support

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#151]
https://github.com/EOSIO/eos/pull/11058 added option to convert snapshots to JSON.
The output format should be changed slightly from what is in that PR so that the resulting JSON can be more easily read. 
Along with 11058, should add the ability to read in the JSON. We have rapid JSON dependency already, so rather straightforward to add read of the JSON.

**Comment by spoonincode** [comment]
Personally I'd like to see this not be lumped in to nodeos. We have an `eosio-blocklog` tool that does all things blocklog, similarly I could see an `eosio-snapshot` tool that does all things snapshot.

For example I'd like to be able to `eosio-snapshot --blocknum snapshot.bin` and just get a simple block number on stdout. With nodeos I'm going to get all sorts of log spam in the output making it a pain to integrate with scripts etc

**Comment by heifner** [comment]
We have talked about a eosio-util for awhile. I do think we want `--snapshot` of nodeos to accept either `.bin` or `.json` files.

**Comment by spoonincode** [comment]
What is the benefit to having nodeos accept a snapshot in json form?

**Comment by heifner** [comment]
You can easily modify the JSON snapshot and then read it into nodeos updating its state.
