### ISSUE TITLE
Replace fc logging with spdlog

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#152]
This work was started, but not finished in https://github.com/EOSIO/eos/pull/11062
* fc logging is slow as everything is converted to variant and then to string.
* fc logging lacks many features of modern logging frameworks: file logging, log rotation, log size limits, logging on differ thread, etc.

**Comment by spoonincode** [comment]
Do we have any metrics on the performance difference? Even unrealistic stuff (constantly log in a while loop for a few seconds? :shrug: ).

**Comment by heifner** [comment]
Moved to leap
