### ISSUE TITLE
Add min-initial-block-num option

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#166]
`min-initial-block-num` option to chain plugin so that nodeos will refuse to load any state from prior to the specified block number.

- https://github.com/EOSIO/eos/pull/10872

**Comment by heifner** [comment]
> I'm not really sure there is much of a general use case for this?

That is why I created this issue. I'm not sure either. If the community wants this, they should speak up.

**Comment by matthewdarwin** [comment]
What is the intended use-case?

**Comment by spoonincode** [comment]
eh it comes about due to Bullish security stuff. I don't really see a general use case for public networks.

**Comment by spoonincode** [comment]
Didn't get any traction. Closing
