### ISSUE TITLE
/v1/chain/get_transaction_status has too detailed of error messages when transaction id is not parseable

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#175]
```
$ curl -sd '{"id": "00"}' https://jungle4.api.eosnation.io/v1/chain/get_transaction_status | jq
{
  "state": "UNKNOWN",
  "head_number": 11807478,
  "head_id": "00b42af653b1f4ba36d52728dac56d0030898fc67f684c638877dce42a03826c",
  "head_timestamp": "2022-05-02T18:02:46.000",
  "irreversible_number": 11807145,
  "irreversible_id": "00b429a95aa59a28ccf04698e52b5ab64a02f86ae4aa68307edaa10fe18cd654",
  "irreversible_timestamp": "2022-05-02T17:59:53.500",
  "last_tracked_block_id": "00b41044645bbc88c2470f83e7ecfd2dec2db1c0e061cf0bb3061dc1c7c6da2e",
  "last_tracked_block_number": 11800644
}
```

This seems incorrect:

```
$ curl -sd '{"id": "0"}' https://jungle4.api.eosnation.io/v1/chain/get_transaction_status | jq
{
  "code": 400,
  "message": "Invalid Request",
  "error": {
    "code": 3200006,
    "name": "invalid_http_request",
    "what": "invalid http request",
    "details": [
      {
        "message": "Unable to parse valid input from POST body",
        "file": "chain_api_plugin.cpp",
        "line_number": 47,
        "method": "parse_params"
      },
      {
        "message": "str.size() % 2 == 0: the length of hex string should be even number",
        "file": "variant.cpp",
        "line_number": 740,
        "method": "from_variant"
      }
    ]
  }
}
```

**Comment by matthewdarwin** [comment]
Providing lots of weird input has lots of different messages.

**Comment by matthewdarwin** [comment]
```
$ curl -sd '{"id": "xx"}' https://jungle4.api.eosnation.io/v1/chain/get_transaction_status | jq
{
  "code": 400,
  "message": "Invalid Request",
  "error": {
    "code": 3200006,
    "name": "invalid_http_request",
    "what": "invalid http request",
    "details": [
      {
        "message": "Unable to parse valid input from POST body",
        "file": "chain_api_plugin.cpp",
        "line_number": 47,
        "method": "parse_params"
      },
      {
        "message": "Invalid hex character 'x'",
        "file": "hex.cpp",
        "line_number": 13,
        "method": "from_hex"
      }
    ]
  }
}
```

**Comment by matthewdarwin** [comment]
Is there a function that just validates if it is a valid transaction id or not, and leaves out all these more detailed messages which seem overly specific?

**Comment by heifner** [comment]
> Is there a function that just validates if it is a valid transaction id or not, and leaves out all these more detailed messages which seem overly specific?

In `cleos`, we added such a message that just says `"Unable to convert " << status_transaction_id << " to transaction id."`

For the server, it just is using standard JSON parser to try and convert to a `transaction_id_type` which is a `sha256` which expects a hex string. `00` is valid hex where `0` is not.  

We could add special handling for this particular endpoint if you think it would help.

**Comment by matthewdarwin** [comment]
"Unable to convert " << status_transaction_id << " to transaction id." sound better, but leave out echoing back the original transaction id. (security risk if someone puts some javascript in there or whatever).

"Invalid transaction id" is simple and clear.

**Comment by aaroncox** [comment]
More descriptive error handling is definitely on my wishlist, for all API endpoints. Whether or not those improved errors make it into the initial version of this API isn't a make or break moment, but could set a good example of how it's done. 

Thoughts would be:

- Invalid JSON (like we have)
- Missing required `id` parameter (if valid json, but no ID)
- Invalid required `id` parameter (if valid JSON and invalid ID)

**Comment by matthewdarwin** [comment]
Seems to work as discussed.
