### ISSUE TITLE
Rename last_tracked_block_id and last_tracked_block_number in get_transaction_status to earliest_*

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#176]
The `last_tracked_block_id` and `last_tracked_block_number` are actually the **earliest** , not the last one?  (last one being the current one). Just seems odd to me.

```
$ curl -sd '{"id": "00"}' https://jungle4.api.eosnation.io/v1/chain/get_transaction_status | jq
{
  "state": "UNKNOWN",
  "head_number": 11807884,
  "head_id": "00b42c8c15d2a75cf8410153b637855e4842dbc18c852446b1dbf783452a41f8",
  "head_timestamp": "2022-05-02T18:06:21.000",
  "irreversible_number": 11807553,
  "irreversible_id": "00b42b41281540815209d6d04c760b4f53ef37c3137c8dd8550f124557912ea4",
  "irreversible_timestamp": "2022-05-02T18:03:29.500",
  "last_tracked_block_id": "00b411ce8263d756c087f9b1b5636d0f05169de3764d7d52e0cd902f3bd284ec",
  "last_tracked_block_number": 11801038
}
```

**Comment by heifner** [comment]
I see your point. Hmm, what about just `traced_block_number` or `earliest_tracked_block_number` or `start_tracked_block_number` or `begin_tracked_block_number` or `the_block_number_that_begins_range_up_to_head_where_we_have_tracked_data`

**Comment by matthewdarwin** [comment]
earliest_ or start_ seems more clear to me.  Should be consistent with https://github.com/eosnetworkfoundation/mandel/issues/118?  I think that uses "first_" which is also fine.

**Comment by aaroncox** [comment]
`earliest_` makes sense to me too. 

`start_` feels like it implies where the status or something started, and `first_` has the same sort of feel.

**Comment by heifner** [comment]
So `earliest_` and name #118 `get_earliest_block_available`.

**Comment by matthewdarwin** [comment]
Testing is blocked, because transaction id seems not valid, no matter what I put there.  @heifner to investigate

**Comment by matthewdarwin** [comment]
Kevin: We have identified the issue. We have some refactoring and an integration test coming for transaction finality. The fix will be included in that. It will be a few days.

**Comment by matthewdarwin** [comment]
Based on initial tests, works as expected. Will open separate issue if anything comes up during testing.

```
$ curl -sd '{"id": "580ae7e21dcc6339d74e342a86d36d9a2bc528c29a6e5bb46ea751d06f6c0e83"}' https://jungle4.api.eosnation.io/v1/chain/get_transaction_status | jq
{
  "state": "IN_BLOCK",
  "block_number": 13471257,
  "block_id": "00cd8e19fc97a24cade9fcccde5a0391185c5689bf2b8751550a6efa48f98743",
  "block_timestamp": "2022-05-12T14:21:34.500",
  "expiration": "2022-05-12T14:22:03.000",
  "head_number": 13471320,
  "head_id": "00cd8e58ca9f4639f2387eac2dcd3158c5438687c4e8480f3a5f0c00e5a479d3",
  "head_timestamp": "2022-05-12T14:22:06.000",
  "irreversible_number": 13470996,
  "irreversible_id": "00cd8d140b4648e55e45668b9be02a2cb2ac210624e05a81718accf73c74f406",
  "irreversible_timestamp": "2022-05-12T14:19:23.500",
  "earliest_tracked_block_id": "00cd727aa88ab7d82b0f5f772822a1fd6bea5ae7322ab7eebf4f543e193b36e3",
  "earliest_tracked_block_number": 13464186
}```
