### ISSUE TITLE
port various nodeos light validation improvements

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#188]
nodeos has the ability to run in light validation mode. In this mode actions are executed but some parts of protocol validation are skipped as if a light client would. For example, checking that the signatures on the transaction fulfill required authorities.

In 2.1 various improvements were made to nodeos' light validation mode. For example (and we'll add more here as discover them):
* https://github.com/EOSIO/eos/pull/8846
* https://github.com/EOSIO/eos/pull/8856
* https://github.com/EOSIO/eos/pull/8847
* https://github.com/EOSIO/eos/pull/8851

The improvements are mostly with regard to not executing context free actions in light validation mode.

I would guess it's fairly rare for someone to run nodeos in light validation mode as it doesn't really improve performance much, so from that standpoint porting these over seems unnecessary. But, these changes do allow exercising and testing important protocol behaviors and on first look seem to be fairly self contained (not intertwined with the functionality that _actually removes_ CFA from block logs, which is something we're definitely not interested in porting!), so maybe it's fine to just bring them along.

EDIT:

We decided not to port https://github.com/EOSIO/eos/pull/8856 or https://github.com/EOSIO/eos/pull/8851.

However, the remaining two items should still be ported. They are tracked by the following two issues:

- [x] https://github.com/eosnetworkfoundation/mandel/issues/556
- [x] https://github.com/eosnetworkfoundation/mandel/issues/557

**Comment by ClaytonCalabrese** [comment]
- [] #556 
- [] #557 
- [] #558 
- [] #559

**Comment by arhag** [comment]
@ClaytonCalabrese: 

I added your list (except without the two issues we don't want to port) into @spoonincode's original comment at the top. By putting the checklist in the original comment, GitHub treats the linked issues in a special way. It treats them as tasks to be completed as part of this larger issue. And also if you visit the individual issues you will see it adds a "Tracked in #188" near the title.

I think this is a good way for us to break up large issues that track bigger items of work (e.g. some big feature or an epic) into smaller tasks that can be started and completed within a biweekly sprint. As the individual tasks are completed, we would make sure that the checkbox is marked to show progress on the larger issue. If all tasks of the larger issue are completed, then we would make sure to also close the larger issue as "Close as completed". That last step is also important in helping us track completion of the larger feature/epic as part of the milestones.

FYI @heifner: want to make sure you also saw the above and get your feedback.
