### ISSUE TITLE
Transaction retry issue (--retry-irreversible = true in cleos)

### ISSUE THREAD

**Issue by jhjhjh94** [eosnetworkfoundation/mandel#215]
-Nodeos config.ini configured with transaction-retry-max-storage-size-gb = 1

Reproduce steps :
1) Have two eos accounts (default in junglenet4 is 100 EOS)
2) Send an overdrawn balance from acc1 to acc2 (101 EOS)
-cleos push action eosio.token transfer '["acc1", "acc2". "101.0000 EOS", ""]' -p acc1 --retry-irreversible true;
3) It hangs without any response
4) While waiting send cleos push action eosio.token transfer '["acc2", "acc1". "1.0000 EOS", ""]' -p acc2
-so that acc1 has sufficient balance.
5) The first transaction will still hang for 3 minutes, then finally shows expired transaction.

**Comment by heifner** [comment]
Introduced by `return_failure_trace` support. Easy fix incoming with a new test for this.
