### ISSUE TITLE
deep_mind in chain_plugin.cpp: allow named pipes

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#221]
it will be practical if deep-mind logs could be sent to a FIFO file instead of stdout. This requires one more configuration option and a small change in plugin initialization: it needs to check that the file exists and is a FIFO pipe, and set it as the logger output.

There's no performance impact, as FIFO is basically the same as stdout, but with a better flexibility. Also the deep-mind reader can disconnect and reconnect to the pipe, without stopping the nodeos.

**Comment by linh2931** [comment]
After extensive discussions, it is decided to not proceed with short-term changes to deep-mind. Please see the details in the 2 PRs.
