### ISSUE TITLE
Run db modes test non-parallelized

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#236]
Backport https://github.com/EOSIO/eos/pull/10736

**Comment by spoonincode** [comment]
db_modes_test should be a parallelized test

**Comment by heifner** [comment]
It writes to the file system and we saw issues with that interfering with other tests.

**Comment by heifner** [comment]
Although, it writes to a temp dir, so no idea why that would have been the case. 🤷 Maybe there was something else going on. I'll close this issue and if it ever fails we can look into it then.
