### ISSUE TITLE
verify (in)compatibility with 2.1 data files for 3.1 release

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#264]
We need to make a pass before 3.1 is released to determine what data files are compatible or incompatible from 2.1 and note this accordingly in the release notes so users can take proper action if they were using 2.1. For example, block logs _created_ by 2.1 will certainly not be supported. I believe any ship log written to by 2.1 will not be compatible, even if created by 2.0.

Unsure if snapshots created by 2.1 import correctly or not. Obviously if 2.1-only protocol features are enabled the snapshot cannot be accepted (what happens though?). But what about 2.1 created snapshots that only have compatible protocol features enabled? Those okay?

What's the situation with trace api data files?

**Comment by heifner** [comment]
`trace_api_plugin` data files from `eosio/eos 2.1.0` and `eosio/eos 2.1.0` should work with Mandel. We should test that, of course.

**Comment by ClaytonCalabrese** [comment]
I've investigated the snapshort portion of this ticket and all the latest snapshots from eosnation work with 3.1, with the exception of jungle3 v5, which enables kv_database, an action we do not have in Mandel.

**Comment by matthewdarwin** [comment]
jungle3 v5 snapshots are not expected to work, so this is good. ;-)

**Comment by matthewdarwin** [comment]
see also: https://github.com/eosnetworkfoundation/mandel/issues/346
