### ISSUE TITLE
Where can I see the development plan?

### ISSUE THREAD

**Issue by cppfuns** [eosnetworkfoundation/mandel#29]
Where can I see development plans? For example, compatible with EVM and RPC implementations, reducing irreversible time?
The most hope is to realize the IBC interoperability of the Ethereum data layer, which can directly transition the existing users of Ethereum

**Comment by tbfleming** [comment]
https://medium.com/edenoneos/eos-mandel-to-takeover-eosio-in-2022-2e25bf5451f0

Other plans: see the upcoming papers from the working groups.
