### ISSUE TITLE
Refactor producer_plugin to remove dup code around push_transaction

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#297]
There are minor differences in the two calls to push_transaction in producer_plugin. These should be combined into one so that critical fixes are not missed by being applied to only one of the code paths.

**Comment by heifner** [comment]
Currently the `push_transaction` in `process_unapplied_trx` does not correctly handle return_failure_trace or log correctly.

**Comment by linh2931** [comment]
When this is being worked on, please add the detailed contract information logging introduced by https://github.com/eosnetworkfoundation/mandel/pull/733.
