### ISSUE TITLE
Integrate verify_rsa_sha256_sig from WAX into mainline mandel

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#310]
It will be great to have the same binary for WAX and EOS, and also potentially let other networks use the `verify_rsa_sha256_sig` intrinsic.

So, best solution: make it possible for the same binary to run for WAX and EOS.

Second-best solution: enable `verify_rsa_sha256_sig` at compile time.

**Comment by arhag** [comment]
Since this is a consensus level change we will not be able to introduce it into 3.2 (a minor version bump relative to 3.1). The earliest we would be able to introduce it is 4.0.

So I am removing the 3.2 Candidate label.

**Comment by cc32d9** [comment]
if it's a compile-time option, it could also be added to 3.2

**Comment by spoonincode** [comment]
will track in AntelopeIO/leap#148
