### ISSUE TITLE
Improve log messages when loading/unloading state

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#318]
When loading or unloading state (startup, shutdown) and config `database-map-mode = heap`, then nodeos prints log messages like:

```
CHAINBASE: Preloading "state" database file, this could take a moment...
               1% complete...
               10% complete...
               18% complete...
               26% complete...
               34% complete...
               41% complete...
```

The % complete messages don't say what is loading or unloading making it harder for log file parsers to know what is going on as you need the context from the "first" line here.

Better would be something like:

```
Loading chainbase, 1% complete
Loading chainbase, 10% complete
```

**Comment by spoonincode** [comment]
would be nice to figure out a clean way to get appbase & chainbase to participate in the standard logging mechanism :thinking:

**Comment by spoonincode** [comment]
submodule hell is my first thought :sweat_smile:   like wouldn't you have to be extra careful that the fc submodule is the same all across chainbase & appbase & mandel to ensure ODR satisfied?

**Comment by heifner** [comment]
Maybe via https://cmake.org/cmake/help/latest/module/FetchContent.html where you specify a mandel wide version of fc.
