### ISSUE TITLE
Enhancement: API request for LIB timestamp

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#32]
this is a copy of https://github.com/EOSIO/eos/issues/10128

This document explains the importance of LIB timestamp for applications:
https://github.com/cc32d9/cc32d9_ideas_for_EOSIO/blob/master/Temporary_history_in_contract_tables.md

Currently LIB timestamp requires two API calls, get_info and get_block, and get_block response is quite bulky sometimes.

The enhancement would bring a cheaper way to retrieve the LIB timestamp: either as a new field in get_info response, or a new API call, like /v1/chain/get_lib which would return the LIB block number, hash and timestamp.

**Comment by swatanabe** [comment]
2.1 has `get_block_info` is a lighter weight alternative to `get_block`.  We should consider backporting it.  I'm very hesitant to add anything to `get_info` without a coherent idea of what should (and more importantly should not) be in it.  We could consider extending `get_block_params` to allow special identifiers like HEAD and LIB.

**Comment by cc32d9** [comment]
sure, a separate call is fine. It just needs to be more efficient than `get_block`, especially that a multi-megabyte block is not uncommon.

**Comment by heifner** [comment]
`get_block_info` PRs
https://github.com/EOSIO/eos/pull/8704
Docs https://github.com/EOSIO/eos/pull/9557
