### ISSUE TITLE
replace boost::filesystem with std::filesystem

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#321]
This transition had been blocked in the past due to macOS 10.14 not supporting std::filesystem. Obviously that's not an issue any longer, and afaik even Ubuntu 18.04 has a working std::filesystem.

- Provide temporary directory support that uses std::filesystem
- Remove fc's wrapper over boost::filesystem and just use std::filesystem directly instead of through fc.

**Comment by spoonincode** [comment]
related eosnetworkfoundation/mandel-fc#47

**Comment by stephenpdeos** [comment]
@larryk85 can you link your appbase PR related to this here?

**Comment by spoonincode** [comment]
Transferred to leap
