### ISSUE TITLE
Enhancement: new API call: is_valid_account

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#33]
this is a copy of https://github.com/EOSIO/eos/issues/9897

`get_account` API call is gathering a lot of information, but in many cases the requestor just needs to check if an account exists on the blockchain.

A new API call is needed that is just returning true or false for a given account name. This will save a lot of CPU time on API servers and clients.

The feature is non-intrusive, and can be added to the current 2.0 software.

An even better option is to take an array of accounts and return an array of valid accounts. But then it needs to take care of response time limits and error handling.

**Comment by stephenpdeos** [comment]
@cc32d9 what is the use case / frequency that is driving your request for a simplified call?

**Comment by cc32d9** [comment]
any mass action, such as airdrop, needs to check if an account exists. So, a cheaper request would save a lot of nodeos time

**Comment by spoonincode** [comment]
Will track in AntelopeIO/leap#591 for now, closing here
