### ISSUE TITLE
Complete 3.1 Release Notes

### ISSUE THREAD

**Issue by tedcahalleos** [eosnetworkfoundation/mandel#331]
Per discussion in 5/31/22's 3/1 Candiidate discussion, the team needs to collaborate to finalize [release notes for 3.1](https://github.com/eosnetworkfoundation/mandel/wiki/3.1-Release-Notes)

**Decisions**
* A finalized set of release notes is not required for the 3.1 RC 1 to be released to Jungle, but should still be considered a high priority

**Upcoming tasks**
* Jonathan Giszczak and Stephen Diesel to sync and make progress on body of release notes OCI has helped deliver
* Matt Witherspoon and Stephen Diesel to sync and make progress on body of release notes he has helped delliver

**Areas of focus**
* Breaking changes, updates that require user actions
* New features
* Clear communication about what aspects of the documentation are still in progress.

**Comment by tedcahalleos** [comment]
- Need SHiP Log and Log pruning section
- Need EVM Section

**Comment by matthewdarwin** [comment]
Release notes are published with mandel 3.1.0-rc1
