### ISSUE TITLE
mandel 3.1 snapshots don't work with eosio 2.1: increase snapshot version number?

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#346]
So I've been testing snapshots, on jungle4. This chain only has features compatible with eosio 2.0 activated.

- snapshots taken with eosio 2.0 work with mandel 3.1
- snapshots taken with eosio 2.1 work with mandel 3.1
- snapshots taken with mandel 3.1 don't work in eosio 2.1

The snapshot version number on 2.1 and 3.1 both "v5". But these are not backwards compatible. Should we bump the version number to "v6?" 

Or they should be backwards compatible?

Error message:

3060005 bad_database_version_exception: Database is an unknown or unsupported version
state database version pre-dates versioning, please restore from a compatible snapshot or replay!

**Comment by matthewdarwin** [comment]
so using the mandel 3.1, I restored a snapshot from:
- 2.0
- 2.1
- 3.1

While running in irreversible mode, they all return the same http://localhost:8888/v1/producer/get_integrity_hash

**Comment by swatanabe** [comment]
It's intended to be compatible, but I only tested loading 2.1 snapshots with 3.0, not the other way around.
