### ISSUE TITLE
Backport txn_test_gen_plugin parameters

### ISSUE THREAD

**Issue by ndcgundlach** [eosnetworkfoundation/mandel#354]
Backport the addition of the following txn_test_gen_plugin parameters:

txn-test-gen-expiration-seconds: configure the transaction expiration time of transaction
txn-test-gen-stop-on-push-failed: configure whether to stop transaction generation when push failed

Original PR: https://github.com/EOSIO/eos/pull/10982

**Comment by arhag** [comment]
This issue was resolved in #355 but brought into the `main` branch via #404.
