### ISSUE TITLE
Build script bash path

### ISSUE THREAD

**Issue by eosusa** [eosnetworkfoundation/mandel#356]
On a fresh Ubuntu 18.04 install I had to update both install_prereqs.sh and pinned_build.sh to have /bin/bash for the path instead of /usr/bin/bash as they failed to launch

**Comment by matthewdarwin** [comment]
Do we need bash at all?  What about just using /bin/sh?

**Comment by spoonincode** [comment]
Resolved in 3.1rc2 :+1:
