### ISSUE TITLE
Expose nodeos config options via admin RPC call

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#360]
Some administrators would like to know how their RPC node is configured.  Would be nice to expose that via RPC call /v1/node/get_config or something.  On a separate listening HTTP port for admin requests, not the standard HTTP port exposed to users.

The returned information should be in json format.  It could return the name of the option, the currently set value, a flag to say if that is the default or not as well as the text describing what the option does.

When adding/removing peers (via cleos net connect ...) , probably the returned configuration should be updated accordingly.

**Comment by spoonincode** [comment]
This will be tracked via eosnetworkfoundation/product#143 and any follow on issues from that
