### ISSUE TITLE
Add subjective limit for mod_exp

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/mandel#361]
https://github.com/eosnetworkfoundation/mandel/issues/182 adds a host function `mod_exp` for modular exponentiation. There are currently no limits on that. It may be necessary to enforce some limits to prevent the actual termination of a transaction from being delayed too much beyond the intended deadline timeout.

Benchmarking should be done to determine what are appropriate permissive limits that prevent a contract from creating too much of a delay (less than a millisecond?) within the process of aborting the transaction. Those limits should then be enforced in the `mod_exp` host function as a subjective exception (meaning it would be enforced at the BPs and not actually part of the protocol).

**Comment by stephenpdeos** [comment]
This is partially dependent on gmp https://github.com/eosnetworkfoundation/mandel/issues/362. Until this is done, we won't be 100% on hardcoded values
