### ISSUE TITLE
pinned builds "build" directory is not relative to the point where the build starts

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#364]
If I run `scripts/pinned_build.sh /local/lib/mandel-3.1 build 8`, I expect the build files in `build` directory relative to the current directory where I start the build.  However, the builds end up in `/local/lib/mandel-3.1/build`

**Comment by linh2931** [comment]
The fix was pulled into main by https://github.com/eosnetworkfoundation/mandel/pull/494. Both release/3.1.x and main have the fix.
