### ISSUE TITLE
pre-compiled binaries for release v2.0.14

### ISSUE THREAD

**Issue by marc0olo** [eosnetworkfoundation/mandel#373]
it seems like they are missing. would be nice if you could provide this :)

**Comment by marc0olo** [comment]
just got a link from Henrik of eossweden:

- https://eosswedenorg.github.io/apt/mandel/bionic/stable/mandel-2014

**Comment by matthewdarwin** [comment]
I think there will be no "official" mandel binaries for 2.0.x.

**Comment by marc0olo** [comment]
yeah, we also built our owns now. was just wondering because they were published in the old "official" eosio repository

**Comment by matthewdarwin** [comment]
Binaries are are available for the 3.1.0-rc1 release.  I expect they will be published going forward.
