### ISSUE TITLE
Investigate Nodeos "End of file" with SHiP Client Test

### ISSUE THREAD

**Issue by ClaytonCalabrese** [eosnetworkfoundation/mandel#374]
When using the SHiP Client test, a "End of file" error is reported in nodeos. The reason for this error is to be investigated and determined whether it is spurious, or whether it indicates an actual issue with how SHiP testing is done.

**Comment by ClaytonCalabrese** [comment]
The "End of file" is the return errorcode from boost when the connection (socket) is closed. This shouldn't be interpreted as an error and so it should be suppressed in on_fail.

**Comment by heifner** [comment]
Resolved by #377
