### ISSUE TITLE
Add command line option --snapshot-to-json

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#39]
https://github.com/EOSIO/eos/pull/11058

**Comment by heifner** [comment]
I agree, we talked a long time about creating something like `eosio-util` which would contain this and other util like command line options of `nodeos`.

**Comment by swatanabe** [comment]
It's also potentially surprising that it loads the snapshot into the current chain state.

**Comment by spoonincode** [comment]
Implemented in AntelopeIO/leap#450
