### ISSUE TITLE
Backport: Reflection validation script

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#391]
https://github.com/EOSIO/eos/pull/8409
https://github.com/EOSIO/eos/pull/9726

This functionality should be brought over but use clang instead of regex.

**Comment by oschwaldp-oci** [comment]
Going to split this into 3 issues, one each for backports and one for the additional change from clang to regex.

**Comment by heifner** [comment]
I think the `FC_REFLECT` macro should be updated to validate that all members are provided to it.
Something like: `FC_REFLECT( x_type, (m_x1)(m_x2), (m_ignored_1) )` 
This can then be enforced by the compiler using `static_assert( sizeof(type) == sizeof(reflected_type) );`

**Comment by heifner** [comment]
Per @larryk85:

> I would recommend that this is just a criteria for PR review (looking at the reflects) and for structs and classes that have fields and methods, have the fields in a consistent section to help with review and updating. I understand that this puts the burden onto the review process and can still have forgotten or missed fields because it is a manual process, but this will still allow for forgotten fields anyway.
