### ISSUE TITLE
Backport: Fix unpack data for signing transaction

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#399]
https://github.com/EOSIO/eos/pull/8931

A failure to sign transactions was reported by https://github.com/EOSIO/eos/issues/8911 on `develop` on April 20, 2020 (`eosio` v 2.0.4 worked). Need to verify if the bug exists on `mandel`. Port the fix if it does.

**Comment by ClaytonCalabrese** [comment]
This bug does not appear to happen on mandel.
