### ISSUE TITLE
lower the level of push_transaction error to info

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#40]
On a public node, the log is full of the following errors:

```
error 2022-02-11T16:23:16.704 nodeos    http_plugin.cpp:964           handle_exception     ] FC Exception encountered while processing chain.push_transaction
```

it is a norm that clients are pushing transactions that fail. Please lower the message priority, so that it doesn't clog the errors and warnings.

**Comment by heifner** [comment]
Fixed by https://github.com/eosnetworkfoundation/mandel/pull/267
