### ISSUE TITLE
plugin_http_api_test improvement

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#406]
https://github.com/eosnetworkfoundation/mandel/pull/387 fixes a race condition in activating a hardcoded list of protocol features by carefully arranging the list to get the test to pass. This needs to be revisited.

**Comment by arhag** [comment]
We don't need to hard-code the protocol features and their digests in the Python file. Instead it can dynamically grab the list of supported protocol features using `get_supported_protocol_features` and then activate them.

**Comment by stephenpdiesel** [comment]
Attempting to re-open and close again to resolve a GitHub bug. Please disregard.
