### ISSUE TITLE
Backport: added a new option fix-irreversible-blocks to eosio-blocklog

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#407]
https://github.com/EOSIO/eos/pull/9245

Provide `--fix-irreversible-blocks` to fix inconsistent block log and index files automatically. This addresses https://github.com/EOSIO/eos/issues/8940.

**Comment by linh2931** [comment]
Please backport https://github.com/EOSIO/eos/pull/10086 at the same time, as it allows no index file.

**Comment by oschwaldp-oci** [comment]
> Please backport [EOSIO/eos#10086](https://github.com/EOSIO/eos/pull/10086) at the same time, as it allows no index file.

Splitting into its own issue: https://github.com/eosnetworkfoundation/mandel/issues/518

**Comment by oschwaldp-oci** [comment]
Blocklog refactor related. May not plan to backport this due to differences with blocklog changes, but instead work it when backlog path forward decided.

**Comment by spoonincode** [comment]
Reversible block DB has been removed in Leap, so this isn't applicable any more
