### ISSUE TITLE
Backport: add first_block_num for cleos get_info

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#414]
https://github.com/EOSIO/eos/pull/10087

**Comment by matthewdarwin** [comment]
This is done already?

![image](https://user-images.githubusercontent.com/26171839/174345688-12d867a7-bdb9-4b9e-a9c0-df3ad2fb0611.png)

**Comment by matthewdarwin** [comment]
see "earliest_available_block_num" in screenshot.

**Comment by linh2931** [comment]
Thanks @matthewdarwin. Looked at the code in Mandel and EOSIO. They refer to the same. 

In Mandel, controller.cpp has
```
   uint32_t earliest_available_block_num() const {
      return (blog.first_block_num() != 0) ? blog.first_block_num() : fork_db.  root()->block_num;
   }
```

In EOSIO 2.2, controller.cpp has

```
uint32_t controller::get_first_block_num()const
{
   return my->blog.get_first_block_num();
}
```

Will close this.
