### ISSUE TITLE
Backport: verify producer name is an eosio name

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#429]
https://github.com/EOSIO/eos/issues/9335

Unmerged PR. Trying to fix a minor issue: when starting a BP and producer name is not presented after '-p' in the command line, the next word is always treated as producer name; for example, given  "-p --data-dir=xxx". nodeos starts with default data-dir instead of given one. https://github.com/EOSIO/eos/issues/9335

**Comment by heifner** [comment]
The associated PR was never finished. This should not be backported. An argument might be made to attempt to fix this by generating a better error message, but a new issue can be opened if anyone trips over this.
