### ISSUE TITLE
Backport: add snapshot_information to producer_plugin test

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#434]
https://github.com/EOSIO/eos/pull/9622

Most of https://github.com/EOSIO/eos/pull/9622 contents have been ported. The new test plugins/producer_plugin/test/test_snapshot_information.cpp was left behind. Need to port it.

**Comment by heifner** [comment]
Refactor of pending_snapshot.?pp also needs brought over.
