### ISSUE TITLE
Ehancement: change default read-mode to head (currently speculative)

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#46]
Most people don't want speculative execution, so it should not be the default.

`read-mode = head` means to undo transaction after each speculative execution of the transaction. 
`read-mode = speculative` (default) undo transactions at the end of the block (when you receive a new block).

Some people have said that the speculative mode should be removed entirely, however I do know there are some people using it, so I wouldn't go that far.

**Comment by spoonincode** [comment]
Speculative mode has been removed in 4.0, closing this out
