### ISSUE TITLE
Backport: Standardize JSON formatting of action data

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#466]
Those two should go together.

https://github.com/EOSIO/eos/pull/10100

old code doing this:
act.data ------can parse to json object ? if yes "data"=json object and hex_data = "hex string"
if no "data" = "hex string"

new code doing this:
act.data ------can parse to json object ? if yes "data"=json object and hex_data = "hex string"
if no "hex_data" = "hex string"

and extract function also some changes correspondingly.

Also, please see related test PR here:

https://github.com/EOSIO/eos/pull/10405

**Comment by heifner** [comment]
This change needs to be done at a major release point and clearly communicated. It affects all clients as it changes the JSON format.

**Comment by linh2931** [comment]
Not saving to `data` field is a breaking backward compatibility change. It is agreed not do it. https://github.com/eosnetworkfoundation/mandel/issues/659 is created to track the `hex_field` change
