### ISSUE TITLE
Backport: fix bug in trace_api_plugin no params returned

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#467]
https://github.com/EOSIO/eos/pull/10449

In trace API plugin, if RPC ABIS are specified with --trace-rpc-abi, the 'params' field of the returned transaction JSON did not exist. This was caused by an exception being thrown in chain::abi_serializer, when the return_value field did not exist, it would thrown an 'Unpack exception' even though action params were serialized correctly.

Backport will also bring in tests/trace_plugin_test.py.

**Comment by 766C6164** [comment]
We do NOT want this. It hides abi yield errors.
