### ISSUE TITLE
Enhancement: change default disable-api-persisted-trx to true (currently false)

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#47]
When transactions arrive to an API, the current default is to update the state and then any other query to the API gets the new state.  In a private node this might be appropriate, but in most cases you don't want the state updated until the transaction makes it into a block.

Therefore: `disable-api-persisted-trx` should be changed to true by default

**Comment by cc32d9** [comment]
I fail to see why `disable-api-persisted-trx`  is even needed. If `read-mode = head`, persistence is disabled anyway.  What was the use case for setting `disable-api-persisted-trx` to true and not setting the read-mode to head?

**Comment by heifner** [comment]
Potentially more efficient, but it is unclear if that is the case. I think we should just remove `speculative` mode, make `head` default,  and remove `disable-api-persisted-trx=false`. In my mind these are anti-patterns that produce more confusion than benefit. I think we should just always rollback a trx after it speculatively executes. Don't provide any option to persist a speculative trx state.

**Comment by heifner** [comment]
`disable-api-persisted-trx` has been removed in leap `release/4.0` with the affect of `disable-api-persisted-trx` is always `true`.
