### ISSUE TITLE
Backport: [statehist] Add additional performance logging

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#473]
Added metrics logging for tracking latency and duration between activities in net_plugin and in state_history_plugin.

https://github.com/EOSIO/eos/pull/10361
https://github.com/EOSIO/eos/pull/10368
https://github.com/EOSIO/eos/pull/10365
https://github.com/EOSIO/eos/pull/9208

- [ ] https://github.com/eosnetworkfoundation/mandel/issues/575
- [x] ~https://github.com/eosnetworkfoundation/mandel/issues/576~
- [x] ~https://github.com/eosnetworkfoundation/mandel/issues/577~
- [x] ~https://github.com/eosnetworkfoundation/mandel/issues/578~

**Comment by ndcgundlach** [comment]
- [ ] [Add separate logging for state history plugin ](https://github.com/eosnetworkfoundation/mandel/issues/575)
- [ ]

**Comment by arhag** [comment]
Since all but one of the linked issues in the task list were closed as not planned (because we do not want to port them to Mandel), there is no point in keeping this issue around. The work we do want to port to Mandel is already captured in https://github.com/eosnetworkfoundation/mandel/issues/575.
