### ISSUE TITLE
Backport: [statehist] [bug] always sending head block instead of block requested

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#474]
https://github.com/EOSIO/eos/pull/10336

This appears to be non applicable to mandel version or possibly already addressed in this PR (needs testing):

https://github.com/eosnetworkfoundation/mandel/pull/472

This should be verified as well

https://github.com/EOSIO/eos/pull/10322

**Comment by heifner** [comment]
I believe this is fixed by #472. There is a new test that verifies requested blocks are returned.
