### ISSUE TITLE
Backport: [statehist] ship: add chain_id to get_status_result_v0

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#476]
ship: add chain_id to get_status_result_v0

https://github.com/EOSIO/eos/pull/8663

Breaking change?

**Comment by spoonincode** [comment]
It looks like this is already in

https://github.com/eosnetworkfoundation/mandel/blob/91bf1f10ef390a846754a0572c223ff13d75fee2/libraries/state_history/include/eosio/state_history/types.hpp#L79-L87

It was done through a binary extension so it should be compatible as long as the client knows how to handle those
https://github.com/eosnetworkfoundation/mandel/blob/91bf1f10ef390a846754a0572c223ff13d75fee2/libraries/state_history/abi.cpp#L14-L22

**Comment by 766C6164** [comment]
Awesome, totally looks like its done, thank you! Closing it.
