### ISSUE TITLE
Deprecation: remove read-mode = read-only option

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#50]
The database read-mode option of read-only is deprecated. The same functionality is now provided by the combination of options: read-mode = head, p2p-accept-transactions = false, and api-accept-transactions = false. The new options provide better control and more clearly define usage.

https://github.com/EOSIO/eos/issues/7597

**Comment by spoonincode** [comment]
Removed in leap 4.0
