### ISSUE TITLE
Backport: allow fix_irreversible_block to without index file

### ISSUE THREAD

**Issue by oschwaldp-oci** [eosnetworkfoundation/mandel#518]
https://github.com/EOSIO/eos/pull/10086

**Comment by oschwaldp-oci** [comment]
Blocklog refactor related. May not plan to backport this due to differences with blocklog changes, but instead work it when backlog path forward decided.

**Comment by spoonincode** [comment]
Reversible block DB has been removed in Leap, so this isn't applicable any more
