### ISSUE TITLE
Backport: Standardize JSON formatting of action data

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#522]
https://github.com/EOSIO/eos/pull/10100

old code doing this:
act.data ------can parse to json object ? if yes "data"=json object and hex_data = "hex string"
if no "data" = "hex string"

new code doing this:
act.data ------can parse to json object ? if yes "data"=json object and hex_data = "hex string"
if no "hex_data" = "hex string"

and extract function also some changes correspondingly.

Also, please see related test PR here:

https://github.com/EOSIO/eos/pull/10405

**Comment by heifner** [comment]
Duplicate of: https://github.com/eosnetworkfoundation/mandel/issues/466

This change needs to be done at a major release point and clearly communicated. It affects all clients as it changes the JSON format.

**Comment by 766C6164** [comment]
Closing as duplicate, thank you!
