### ISSUE TITLE
Backport: Various misc logging changes

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#525]
There are number of very closely related PR's with logging changes. They need to be investigated and if deemed usable, cherry picked into mandel

https://github.com/EOSIO/eos/pull/10726
https://github.com/EOSIO/eos/pull/10716
https://github.com/EOSIO/eos/pull/10715

**Comment by ClaytonCalabrese** [comment]
These PR's aren't needed because they are merged into the [pdr/EPE-9](https://github.com/EOSIO/eos/tree/pdr/EPE-9) branch which is included in  https://github.com/eosnetworkfoundation/mandel/issues/148
