### ISSUE TITLE
Backport: Transaction Sponsorship - Send all the available authorizations to the preexecution hook action

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#528]
Change authorization information available to the preexecution hook action, and make all the known authorizers that signed the transaction, be available to it.

Please refer to 2 closely related PR's:

https://github.com/EOSIO/eos/pull/10240

https://github.com/EOSIO/eos/pull/10204

**Comment by heifner** [comment]
I assumed we would not want this backported. @arhag @larryk85 @spoonincode
