### ISSUE TITLE
Backport: Trace API plugin - Add support for action return values

### ISSUE THREAD

**Issue by 766C6164** [eosnetworkfoundation/mandel#529]
Please refer to this PR:

https://github.com/EOSIO/eos/pull/9547

From it's description:
The intent of this PR is to add support to the trace api plugin for a new field representing a value that may be returned by an action.

To accomplish this task 3 new structs were added:

action_trace_v1 : representing the new version of an action trace that now may contain a field representing the return value.

transaction_trace_v2: representing the new version for the transaction trace that supports action_trace_v1.

block_trace_v2: representing the new version for block trace that supports transaction_trace_v2.

The general idea is that, for example, a new version for action traces may now not require the creation of new structs for transaction trace and block trace, but only a modification to the actions type on the transaction trace struct (add a new possibility for the variant).

**Comment by heifner** [comment]
Already done.
Resolved by: #231
