### ISSUE TITLE
Backport: add light validation sync test

### ISSUE THREAD

**Issue by ClaytonCalabrese** [eosnetworkfoundation/mandel#558]
backports: https://github.com/EOSIO/eos/pull/8851

> Add an integration test for messaging syncing between a production node and a light validation node.

**Comment by heifner** [comment]
This was part of prunable CFD which is not needed in Mandel.

**Comment by arhag** [comment]
@heifner: I reopened this issue so that I could close it the correct way for tracking purposes: "Closed as not planned".

**Comment by heifner** [comment]
> @heifner: I reopened this issue so that I could close it the correct way for tracking purposes: "Closed as not planned".

Thanks. I didn't realize there was two ways to close an issue.
