### ISSUE TITLE
Upgrade to C++20

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/mandel#562]

**Comment by spoonincode** [comment]
Some c++20 features are still not supported by various compilers (or supported in one and not the other). It would be nice to draw the line at gcc 10 so we can still support users building easily on Ubuntu 20.04.

**Comment by arhag** [comment]
C++20 would mean requiring pinned builds for Ubuntu 18. It isn't a rush to get C++20 support. I would rather us first prioritize making the changes to get a single linux binary and make the chainbase environent version less fragile (not depend on compiler version and use a Boost headers embedded in repo) so that we can drop the distinction between unpinned and pinned builds.

Then we can upgrade C++20 and still have regular builds of the single linux binary nodeos run on older platforms like Ubuntu 18.

**Comment by greg7mdp** [comment]
superseded by https://github.com/AntelopeIO/leap/issues/922

**Comment by spoonincode** [comment]
closing due to being tracked in leap
