### ISSUE TITLE
backport: p2p timeout  from 2.1

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#58]
**EOSUSA Michael, [14.03.22 10:48]
i think there were 2 parts... one is the p2p issue where it would get all peers unlinkable....  did the fixes also include anything related to the original issue where the p2p sessions hang open for 15min (which is what triggers all those unlinkable blocks in the first place)

Kevin Heifner, [14.03.22 10:49]
The timeout feature is in 2.1, it will need to be back-ported to Mandel**

**Comment by heifner** [comment]
Included as part of https://github.com/eosnetworkfoundation/mandel/pull/169
