### ISSUE TITLE
desubmodularize mandel repo

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/mandel#585]
Do not start until 3.1.0 stable is released.

**Comment by stephenpdeos** [comment]
Blocked by further research in https://github.com/eosnetworkfoundation/product/issues/24

**Comment by spoonincode** [comment]
I'd like to go ahead and close this as in 3.2.0 we've desubmodularized the only submodules we could agree on at the moment. I'd like to see more, but they will need to be handled on a case-by-case basis.
