### ISSUE TITLE
Remove default config-dir and data-dir

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#589]
Currently `nodeos` uses default locations of:
* `config-dir` => `~/.local/share/eosio/nodeos/config` 
* `data-dir` => `~/.local/share/eosio/nodeos/data`

This can often cause confusion as it is not obvious which `config.ini` is being used or what protocol features are in play. This can especially be confusing when upgrading and configuration options need to be updated.

Propose deprecating these defaults in 3.2 and removing them in 4.0. 
For 3.2 add a warning message, something like: `WARNING: default config-dir is deprecated the current location of  .local/share/eosio/nodeos/config/ will need to be explicitly specified in the future.` Similarly for data-dir.
The default can be removed in 4.0 and `config-dir` & `data-dir` change to being required.

These defaults is what caused this issue: https://github.com/eosnetworkfoundation/mandel/issues/553

**Comment by spoonincode** [comment]
> This can often cause confusion as it is not obvious which config.ini is being used

There should be something on start up such as
```
info  2022-07-05T15:40:04.616 nodeos    main.cpp:139                  main                 ] nodeos using configuration file /home/bigdog/.local/share/eosio/nodeos/config/config.ini
info  2022-07-05T15:40:04.616 nodeos    main.cpp:140                  main                 ] nodeos data directory is /home/bigdog/.local/share/eosio/nodeos/data
```
but I think it's printed rather late (nodeos can fail before it's printed).

**Comment by spoonincode** [comment]
Every other blockchain daemon I'm familiar with (eg bitcoind, geth, monerod) does _not_ require config & data directories to be specified on the command line -- they use defaults and allow customization just like we do today.

As part of our long term vision of being able to "just run it", requiring users to manually set these directories seems antithetical to that.

It really just seems like this was a broken test. Perhaps CI should have `$HOME/local` gated off to detect misbehaving tests (we don't want tests to clobber someone's clean nodeos files).

**Comment by stephenpdeos** [comment]
Discarding due to prev comments.
