### ISSUE TITLE
deep-mind writes packed transaction instead of signed one on DTRX_OP PUSH_CREATE  

### ISSUE THREAD

**Issue by fschoell** [eosnetworkfoundation/mandel#651]
Looking at the deep-mind plugin, the version that has been integrated into eosio v2.1 writes signed transactions into the dmlog on `PUSH_CREATE` deferred transactions, see [here](https://github.com/EOSIO/eos/blob/release/2.1.x/libraries/chain/transaction_context.cpp#L695).

The current mandel seems to use the packed transaction instead though, see [here](https://github.com/eosnetworkfoundation/mandel/blob/main/libraries/chain/deep_mind.cpp#L225). This should be only used for `MODIFY_CREATE` while `PUSH_CREATE` should write the signed transaction.

**Comment by heifner** [comment]
Resolved by #654
