### ISSUE TITLE
Duplicate digest in expected_digest_list of plugin_http_api_test.py

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#664]
While working on https://github.com/eosnetworkfoundation/mandel/issues/462, I noticed in `plugin_http_api_test.py`, `expected_digest_list` contains duplicate digest `4fca8bd82bbd181e714e283f83e1b45d95ca5af40fb89ad3977b653c448f78c2` (of `WEBAUTHN_KEY`). As a result, `BLOCKCHAIN_PARAMETERS`'s digest was missing. This is not a serious problem. It just causes `BLOCKCHAIN_PARAMETERS` is not verified in the test. No need to put into Rel 3.1.x.

**Comment by arhag** [comment]
May be something that is automatically resolved by the improvements of https://github.com/eosnetworkfoundation/mandel/issues/406.

**Comment by linh2931** [comment]
Fixed by https://github.com/eosnetworkfoundation/mandel/pull/725.
