### ISSUE TITLE
Document protocol feature activation procedure

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#665]
On the `Mandel upgrade weekly huddle` call of July 13th, 2022 there was a request for documentation on the procedure to activate the new protocol features in Mandle 3.1.

**Comment by linh2931** [comment]
Please review https://hackmd.io/1IgAA-SeShm71_7J6jCxiw#Activating-Protocol-Features

**Comment by linh2931** [comment]
Oha, that's in an internal draft page. Let me paste it here. Thanks.

### Activating Protocol Features


1. #### Activate special protocol PREACTIVATE_FEATURE

All protocol features require a special protocal feature called PREACTIVATE_FEATURE. To activate it, run

```
curl --request POST \
    --url http://<RPC_ENDPOINT_IP_PORT>/v1/producer/schedule_protocol_feature_activations \
    -d '{"protocol_features_to_activate": ["0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd"]}'
```
2. #### Install eosio.boot System Contract
System smart contract `eosio.boot` is required for pushing `activate` command. To install the contract, run

```
./cleos set contract eosio <EOSIO_SYSTEM_CONTRACTS_DIRECTORY>/eosio.boot/bin/ eosio.boot.wasm eosio.boot.abi
```

3. #### Activate Protocol Features

Use `activate` action with a protocol feature's digest as an input to activate.

To get the a list of digests, run 
```
curl -X POST http://<RPC_ENDPOINT_IP_PORT>/v1/producer/get_supported_protocol_features | jq .
```
and look for `feature_digest` field for each protocol feature.

New features introduced in Rel `3.0.x` and `3.1.x` do not have dependencies. You can use any order to activate them. For example

```
# ACTION_RETURN_VALUE
./cleos push action eosio activate '["c3a6138c5061cf291310887c0b5c71fcaffeab90d5deb50d3b9e687cead45071"]' -p eosio

# CONFIGURABLE_WASM_LIMITS2
./cleos push action eosio activate '["d528b9f6e9693f45ed277af93474fd473ce7d831dae2180cca35d907bd10cb40"]' -p eosio

# BLOCKCHAIN_PARAMETERS
./cleos push action eosio activate '["5443fcf88330c586bc0e5f3dee10e7f63c76c00249c87fe4fbf7f38c082006b4"]' -p eosio

# GET_CODE_HASH
./cleos push action eosio activate '["bcd2a26394b36614fd4894241d3c451ab0f6fd110958c3423073621a70826e99"]' -p eosio

# CRYPTO_PRIMITIVES
./cleos push action eosio activate '["6bcb40a24e49c26d0a60513b6aeb8551d264e4717f306b81a37a5afb3b47cedc"]' -p eosio

# GET_BLOCK_NUM
./cleos push action eosio activate '["35c2186cc36f7bb4aeaf4487b36e57039ccf45a9136aa856a5d569ecca55ef2b"]' -p eosio
```

**Comment by stephenpdeos** [comment]
Since this has been added to release notes, closing this issue
