### ISSUE TITLE
Enhancement: add prometheus exporter plugin that exposes key nodeos metrics

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#67]
Copy from: https://github.com/EOSIO/eos/issues/9902

or monitoring, nodeos should have a prometheus exporter plugin (that runs on a separate port), which exposes key metrics that would be useful for monitoring.

Metrics such as

    what is returned from /v1/chain/get_info (head block number, lib)
    unapplied transaction queue sizes
    blacklisted transactions size
    subjective billing sizes
    scheduled transaction size
    number of forks by producer
    number of unapplied blocks by producer
    number of dropped blocks by producer
    number of missed blocks (missed in a round) by producer
    number of missing producers (missed 12 blocks in a round) by producer
    number of double production (more than 12 blocks in a round) by producer
    average (and last) block arrival time by producer
    number of transactions per block by producer
    amount of blockchain cpu used per block by producer
    number of bytes per block by producer
    number of bad actors which have exceeded their transaction limit (as per the changes introduced in nodeos 2.0.9)
    number of clients connected (inbound, outbound, failed)
    number of api (failed) requests/sec (by request type)
    uptime
    cpu usage by thread
    disk space used, by volume (blocks, ship, state, trace)
    disk space available
    rocksdb related
    blockvault related (produced block, vs did not produce because other nodeos "won")
    replay status (when starting from snapshot and replaying blocks)
    etc..

Where possible, attribute actions to a specific producer (eg when counting dropped blocks, specify which producer missed those blocks)

**Comment by spoonincode** [comment]
Part of Leap 4.0
