### ISSUE TITLE
Document Execution instance design and developer impact

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/mandel#673]
In early discussions around Sync Calls, the concept of Execution instances has been introduced as a potential solution design. There have been expressed concerns from the internal team about this tradeoff in improving novice developer quality of life over the paradigm shift experienced devs will have to go through to accomodate this change.

We need to clearly articulate the purpose and structure of the proposed design in order to be able to solicit feedback from the community about the impact it will have before proceeding further.

**Comment by spoonincode** [comment]
I'm going to close this out since, as already mentioned, there is a separate process & repo for tracking large feature proposals throughout their stages. Time spent working on that for sync call feature can be captured appropriately when the time comes.
