### ISSUE TITLE
txn_test_gen_plugin assumes access to build-dir

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#681]
txn_test_gen_plugin looks like it suffers from the same problem that libtester had fixed in #680: it does something like
```c++
abi_def currency_abi_def = fc::json::from_string(contracts::eosio_token_abi().data()).as<abi_def>();
```
but `contracts::eosio_token_abi()` reads from the build-dir. So txn_test_gen_plugin hasn't been usable from a binary packaged build in... a long time.. I'm guessing.

Perhaps eosio_token should additionally be made an embedded contract as libtester's bios contracts. But embedded contracts are currently being placed in libtester: we don't want to make nodeos depend on libtester (if it already doesn't...).

**Comment by heifner** [comment]
Resolved by https://github.com/AntelopeIO/leap/pull/634
