### ISSUE TITLE
Enhancement: Add unique error message for subjective billing in the transaction trace logs

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#682]
When looking at the failed transaction logging, for the error message "Transaction exceeded the current CPU usage limit imposed on the transaction", is that only returned for Subjective Billing?  Or if used for multiple things, can the software be easily changed so Subjective Billing get its own unique error?

**Comment by heifner** [comment]
"Transaction exceeded..." is for any CPU exceeded. `account_cpu_limit = objective_account_cpu - subjective_cpu`.  To provide a different exception in this case, one approach would be to see if `subjective_cpu>0` (if subjective billing enabled) and in that case generate a different exception. Could be something like "Transaction exceeded the current CPU usage limit on the transaction, with a subjective cpu of xus".

Is a different exception in this case considered an interface change?

**Comment by stephenpdeos** [comment]
Team consensus that this would not be an interface change because the solution we will choose will be via change in logging and will not change the exception code. Targeting as a 3.2 candidate.
