### ISSUE TITLE
Disable contract builder step in GitHub actions for PRs from forks

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/mandel#712]
GitHub actions does not provide secrets for CICD running on PRs from forked repositories for security reasons. This causes the "Ubuntu 20.04 | Contract Builder Docker" job to fail.

Since that job is not critical to passing the remaining tests for this repository, we should consider skipping that job on CICD runs for PRs from forked repositories.

**Comment by spoonincode** [comment]
Seems like dupe of #711

**Comment by arhag** [comment]
Oops. Thanks @spoonincode.
