### ISSUE TITLE
Update, Replace, and Check Validity of WASM files in mandel

### ISSUE THREAD

**Issue by ClaytonCalabrese** [eosnetworkfoundation/mandel#729]
A sweep needs to be done of the WASM files in mandel. Certain ones appear to be out of date and not currently compatible with the head of mandel CDT. These should be replaced with modern versions of the wasm, as well as have a way of building the wasm as part of the build step.

**Comment by heifner** [comment]
Test contract build enabled by: `-DEOSIO_COMPILE_TEST_CONTRACTS=true`
