### ISSUE TITLE
Spike: Design for new eosio-util tool

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/mandel#781]
Figure out extensible framework for enabling command line tool that enables nested subcommands with positional and optional arguments, help descriptions, and possibly code completion to use in a new eosio-util tool (and possible in the future as a replacement for the ad-hoc framework used in cleos).

Enumerate initial desired functionality (to be pulled from nodeos, eosio-blocklog, or other programs in the repository dealing with nodeos on-disk files) to capture in this new tool and figure out subcommand breakdown within the tool to capture this functionality.

**Comment by stephenpdiesel** [comment]
@766C6164 to submit proposal PR by EOW to close out this issue

**Comment by vladtr** [comment]
@stephenpdeos - draft proposal PR is here:

https://github.com/eosnetworkfoundation/product/pull/72
