### ISSUE TITLE
Enhance all regression python tests to verify clean shutdown 

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#793]
Currently most of the regression python tests `kill -9` on a successful test. In order to get better coverage around clean shutdown, the `TestHelper.shutdown` should be modified to first `kill -15` and verify clean exit as part of the test. Errors should be reported so that issues with shutdown segfaulting/aborting can be more readily found. This would be a simple change to the current regression suite which would provide additional coverage over a common issue in nodeos.

**Comment by spoonincode** [comment]
will track in leap now
