### ISSUE TITLE
Enhance all regression python tests to run in heap mode

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#794]
Most of the regression python tests run with the default `database-map-mode` of `mapped`. `heap` mode is increasing used and recommended as the `database-map-mode` for most uses. The regression suite should be enhanced to run most/all of the tests in `heap` mode. Consider randomly picking a `database-map-mode` when running regression tests. Alternatively we could create a `heap` mode of all the existing tests, but this seems rather expensive.  Also consider just switching all tests to run in `heap` mode instead; giving less coverage for the default `mapped` mode.

**Comment by stephenpdeos** [comment]
In the future we may consider changing the default mode to heap based on its better performance, but presently this is working as designed in alignment with the default mode currently set.
