### ISSUE TITLE
Reduce debug logging of removed expired transactions during replay

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#802]
During replay with default logger at debug level a log statement for every block is produced:
`removed ${n} expired transactions of the ${t} input dedup list`

![image](https://user-images.githubusercontent.com/3933649/183901673-af754f16-4c1e-4e90-b3df-c4ddf2c60232.png)

Do not log this statement during replay.

**Comment by stephenpdeos** [comment]
Discarding this issue because it works as designed.
