### ISSUE TITLE
3.x pinned build may want to integrate boost 1.70 websocket fix

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#816]
The pinned build is using boost 1.70. This version has a defect in the websocket impl that can cause crashes
```
https://github.com/boostorg/beast/issues/1599
```
We may want to integrate the patch in to our pinned build.

That said, previous releases of EOSIO used:

| EOSIO         | Boost     |
|--------------|-----------|
| 1.8 | 1.70      |
|2.0 | 1.71  |
|2.1 | 1.72  |

I don't recall reports of issues in the 1.8 timeframe. Then again that was a long time ago.

**Comment by stephenpdiesel** [comment]
Should be considered for 3.1.1 but not justifying the release by itself
