### ISSUE TITLE
chain_plugin, chain_api_plugin: a request for retrieving linked permissions

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/mandel#83]
At the moment the RPC does not provide a function that lists an account's linked permissions (the result of linkauth action).. 

Such a request needs to be added to chain_plugin and chain_api_plugin

**Comment by heifner** [comment]
https://github.com/EOSIO/eos/pull/10832
https://github.com/EOSIO/eos/pull/10877

**Comment by heifner** [comment]
Resolved by #237
