### ISSUE TITLE
Enhancement: allow arbitrary list of args to pass to the gelf logger in logging.json

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#91]
the logging.json gelf logger accepts two "args" right now "endpoint" and "host".  "host" is passed through in the log output. 
I would like to pass additional "args" through to the output, like the "network" or the "block producer".  

Workaround: put everything in the "host" field and parse it on the receiving end.

**Comment by matthewdarwin** [comment]
If not arbitrary, then just add 2 new ones: `operator` and `network`.

**Comment by jgiszczak** [comment]
Reopening until the fc submodule is updated in this repository.

**Comment by matthewdarwin** [comment]
Just adding a note here related to testing: https://github.com/eosnetworkfoundation/mandel/issues/319
